# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mock' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CrossroadRegex'
  # Pods for Mock

  target 'MockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
